import { useState, useEffect, useRef, useMemo } from "react";
import { C, BUDGET_CATS, PORTFOLIOS } from "../utils/constants";
import { uid, fmt, fmtPct, MN, today, toKey } from "../utils/helpers";
import { Icons } from "../components/Icons";
import { Card, Empty, Pill, FAB, ProgressBar, DonutChart, Sparkline, CatIcon, SumCard, MiniStat, Backdrop, ModalSheet, SubmitBtn, SegToggle, inputStyle, focusBorder, blurBorder } from "../components/ui";
import { fetchNewsFeed } from "../services/DataService";
export function BudgetModule({ transactions, setTransactions, monthlyBudget, setMonthlyBudget, investments, setInvestments }) {
  const [sub, setSub] = useState("budget");
  return (<div><div style={{ padding: "16px 20px 0" }}><h1 style={{ fontSize: 34, fontWeight: 700, letterSpacing: -0.5, margin: 0 }}>Finances</h1></div>
    <SegToggle options={[{ id: "budget", label: "Budget" }, { id: "invest", label: "Investissements" }, { id: "feed", label: "Actu" }]} active={sub} onChange={setSub} />
    {sub === "budget" && <BudgetSub transactions={transactions} setTransactions={setTransactions} monthlyBudget={monthlyBudget} setMonthlyBudget={setMonthlyBudget} />}
    {sub === "invest" && <InvestSub investments={investments} setInvestments={setInvestments} />}
    {sub === "feed" && <NewsFeed investments={investments} />}
  </div>);
}
function NewsFeed({ investments }) {
  const [articles, setArticles] = useState([]); const [loading, setLoading] = useState(false);
  const keywords = investments.flatMap((p) => { const d = PORTFOLIOS.find((x) => x.id === p.id); return d?.keywords || []; });
  const refresh = async () => { setLoading(true); const data = await fetchNewsFeed(keywords); setArticles(data); setLoading(false); };
  useEffect(() => { refresh(); }, []);
  return (<div style={{ padding: "0 20px 20px" }}>
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><Icons.Rss size={16} color={C.accent} /><span style={{ fontSize: 13, fontWeight: 600, color: C.text2, textTransform: "uppercase", letterSpacing: 0.5 }}>Fil d'actualit&eacute;</span></div><button onClick={refresh} disabled={loading} style={{ background: C.accentLight, border: "none", borderRadius: 8, padding: "5px 12px", fontSize: 12, fontWeight: 600, color: C.accent, cursor: "pointer" }}>{loading ? "..." : "Rafra\u00eechir"}</button></div>
    {articles.length === 0 ? <Card><div style={{ padding: "32px 20px", textAlign: "center" }}><div style={{ fontSize: 40, marginBottom: 12 }}>{"\u{1F4E1}"}</div><div style={{ fontSize: 15, fontWeight: 600, marginBottom: 6 }}>Flux non connect&eacute;</div><div style={{ fontSize: 13, color: C.text3, lineHeight: 1.5 }}>Le fil sera aliment&eacute; une fois le backend Cloudflare connect&eacute;.</div><div style={{ marginTop: 12, display: "flex", flexWrap: "wrap", gap: 6, justifyContent: "center" }}>{keywords.slice(0, 6).map((kw, i) => (<span key={i} style={{ fontSize: 11, background: C.accentLight, color: C.accent, padding: "3px 10px", borderRadius: 6, fontWeight: 500 }}>{kw}</span>))}</div></div></Card> : articles.map((a, i) => (<Card key={i} style={{ marginBottom: 8 }}><a href={a.url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: "none", color: C.text, display: "block", padding: "14px 16px" }}><div style={{ fontSize: 14, fontWeight: 600, lineHeight: 1.4, marginBottom: 6 }}>{a.title}</div><div style={{ fontSize: 12, color: C.text3, display: "flex", gap: 8 }}><span>{a.source}</span><span>{a.date}</span></div></a></Card>))}
  </div>);
}
function BudgetSub({ transactions, setTransactions, monthlyBudget, setMonthlyBudget }) {
  const [showAdd, setShowAdd] = useState(false); const [view, setView] = useState("overview"); const [editB, setEditB] = useState(false);
  const cm = today.getFullYear() + "-" + String(today.getMonth() + 1).padStart(2, "0");
  const mTx = transactions.filter((t) => t.date.startsWith(cm));
  const tIn = mTx.filter((t) => t.type === "income").reduce((s, t) => s + t.amount, 0);
  const tOut = mTx.filter((t) => t.type === "expense").reduce((s, t) => s + t.amount, 0);
  const bal = tIn - tOut; const uP = monthlyBudget > 0 ? (tOut / monthlyBudget) * 100 : 0;
  const bC = uP > 100 ? C.red : uP > 80 ? C.orange : C.accent;
  const ec = useMemo(() => { const m = {}; mTx.filter((t) => t.type === "expense").forEach((t) => { m[t.category] = (m[t.category] || 0) + t.amount; }); return Object.entries(m).map(([id, total]) => { const cat = BUDGET_CATS.expense.find((c) => c.id === id) || { label: id, icon: "\u{1F4E6}", color: C.text3 }; return { ...cat, total }; }).sort((a, b) => b.total - a.total); }, [mTx]);
  return (<div>
    <div style={{ padding: "0 20px" }}><ProgressBar value={tOut} max={monthlyBudget} label={Math.round(uP) + "% utilis\u00e9"} color={bC} /></div>
    <div style={{ padding: "12px 20px 8px", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 15, fontWeight: 600, color: C.text2 }}>{MN[today.getMonth()]} {today.getFullYear()}</span><button onClick={() => setEditB(!editB)} style={{ background: C.accentLight, border: "none", borderRadius: 8, padding: "5px 12px", fontSize: 13, fontWeight: 600, color: C.accent, cursor: "pointer" }}>Objectif : {fmt(monthlyBudget)}</button></div>
    {editB && <div style={{ padding: "0 20px 12px" }}><Card><div style={{ padding: 16 }}><label style={{ fontSize: 13, color: C.text2 }}>Budget mensuel (&euro;)</label><input type="number" value={monthlyBudget} onChange={(e) => setMonthlyBudget(Number(e.target.value) || 0)} style={{ ...inputStyle, fontSize: 20, fontWeight: 700, marginTop: 8 }} /><button onClick={() => setEditB(false)} style={{ marginTop: 10, padding: "8px 16px", background: C.accent, color: "white", border: "none", borderRadius: 8, fontSize: 14, fontWeight: 600, cursor: "pointer", width: "100%" }}>OK</button></div></Card></div>}
    <div style={{ display: "flex", gap: 10, padding: "4px 20px 12px" }}><SumCard label="Revenus" amount={tIn} color={C.green} icon={<Icons.ArrowUp size={14} color={C.green} />} /><SumCard label="D\u00e9penses" amount={tOut} color={C.red} icon={<Icons.ArrowDown size={14} color={C.red} />} /><SumCard label="Solde" amount={bal} color={bal >= 0 ? C.green : C.red} /></div>
    <div style={{ display: "flex", gap: 8, padding: "4px 20px 12px" }}><Pill label="Vue d'ensemble" active={view === "overview"} onClick={() => setView("overview")} color={C.accent} /><Pill label="Transactions" active={view === "details"} onClick={() => setView("details")} color={C.accent} /></div>
    {view === "overview" ? <div style={{ padding: "0 20px 20px" }}><Card><div style={{ padding: "14px 16px 8px" }}><span style={{ fontSize: 13, fontWeight: 600, color: C.text2, textTransform: "uppercase", letterSpacing: 0.5 }}>R&eacute;partition</span></div>{ec.length === 0 ? <Empty text="Aucune d\u00e9pense" /> : ec.map((cat, i) => (<div key={cat.id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", borderTop: i > 0 ? ".5px solid " + C.separator : "none" }}><CatIcon icon={cat.icon} color={cat.color} /><div style={{ flex: 1 }}><div style={{ fontSize: 15, fontWeight: 500 }}>{cat.label}</div><div style={{ height: 3, background: C.separator, borderRadius: 2, marginTop: 5, overflow: "hidden" }}><div style={{ width: tOut > 0 ? (cat.total / tOut) * 100 + "%" : "0%", height: "100%", background: cat.color, borderRadius: 2 }} /></div></div><div style={{ fontSize: 15, fontWeight: 600 }}>{fmt(cat.total)}</div><div style={{ fontSize: 12, color: C.text3, minWidth: 36, textAlign: "right" }}>{tOut > 0 ? Math.round((cat.total / tOut) * 100) : 0}%</div></div>))}</Card></div>
    : <div style={{ padding: "0 20px 20px" }}><Card>{mTx.length === 0 ? <Empty text="Aucune transaction" /> : [...mTx].sort((a, b) => b.date.localeCompare(a.date)).map((tx, i) => { const ac = [...BUDGET_CATS.income, ...BUDGET_CATS.expense]; const cat = ac.find((c) => c.id === tx.category) || { icon: "\u{1F4E6}", color: C.text3 }; const isIn = tx.type === "income"; return (<div key={tx.id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", borderTop: i > 0 ? ".5px solid " + C.separator : "none" }}><CatIcon icon={cat.icon} color={cat.color} /><div style={{ flex: 1 }}><div style={{ fontSize: 15, fontWeight: 500 }}>{tx.label}</div><div style={{ fontSize: 12, color: C.text3, marginTop: 2 }}>{new Date(tx.date).toLocaleDateString("fr-BE", { day: "numeric", month: "short" })}</div></div><div style={{ fontSize: 15, fontWeight: 600, color: isIn ? C.green : C.text }}>{isIn ? "+" : "\u2212"}{fmt(tx.amount)}</div><button onClick={() => setTransactions((p) => p.filter((t) => t.id !== tx.id))} style={{ background: "none", border: "none", cursor: "pointer", padding: 4, opacity: 0.4, display: "flex" }}><Icons.Trash size={16} color={C.text3} /></button></div>); })}</Card></div>}
    <FAB onClick={() => setShowAdd(true)} />{showAdd && <AddTxModal onAdd={(tx) => { setTransactions((p) => [{ id: uid(), ...tx }, ...p]); setShowAdd(false); }} onClose={() => setShowAdd(false)} />}
  </div>);
}
function InvestSub({ investments, setInvestments }) {
  const [selId, setSelId] = useState(null); const [showUp, setShowUp] = useState(false);
  const tI = investments.reduce((s, p) => s + p.invested, 0); const tV = investments.reduce((s, p) => s + p.currentValue, 0);
  const tG = tV - tI; const tPct = tI > 0 ? ((tV - tI) / tI) * 100 : 0;
  const segs = investments.map((p) => ({ pct: tV > 0 ? (p.currentValue / tV) * 100 : 0, color: PORTFOLIOS.find((x) => x.id === p.id)?.color || C.text3 }));
  const ad = investments.flatMap((p) => (p.history || []).map((h) => new Date(h.date).getTime())).filter(Boolean);
  const lu = ad.length > 0 ? Math.max(...ad) : 0; const ds = lu ? Math.floor((Date.now() - lu) / 864e5) : 999;
  const hUp = (pid, nv) => { setInvestments((pr) => pr.map((p) => p.id !== pid ? p : { ...p, currentValue: nv, history: [...(p.history || []), { date: toKey(new Date()), invested: p.invested, value: nv }] })); setShowUp(false); };
  return (<div>
    {ds >= 25 && <div style={{ margin: "0 20px 12px", padding: "12px 16px", borderRadius: 12, background: C.orangeLight, display: "flex", alignItems: "center", gap: 10 }}><Icons.Clock size={18} color={C.orange} /><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 600, color: C.orange }}>MAJ mensuelle</div><div style={{ fontSize: 12, color: C.text2, marginTop: 2 }}>{lu ? ds + " jours" : "Jamais"}</div></div><button onClick={() => setShowUp(true)} style={{ background: C.orange, color: "white", border: "none", borderRadius: 8, padding: "6px 12px", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>MAJ</button></div>}
    <div style={{ padding: "0 20px 12px" }}><Card><div style={{ padding: "20px 16px", display: "flex", alignItems: "center", gap: 20 }}><div style={{ position: "relative" }}><DonutChart segments={segs} /><div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}><div style={{ fontSize: 11, color: C.text2 }}>Total</div><div style={{ fontSize: 18, fontWeight: 700 }}>{fmt(tV)}</div></div></div><div style={{ flex: 1 }}><div style={{ fontSize: 13, color: C.text2, marginBottom: 4 }}>Performance</div><div style={{ fontSize: 24, fontWeight: 700, color: tG >= 0 ? C.green : C.red }}>{tG >= 0 ? "+" : ""}{fmt(tG)}</div><div style={{ fontSize: 14, color: tPct >= 0 ? C.green : C.red, fontWeight: 600, marginTop: 2 }}>{fmtPct(tPct)}</div><div style={{ fontSize: 12, color: C.text3, marginTop: 6 }}>Investi : {fmt(tI)}</div></div></div><div style={{ padding: "0 16px 16px", display: "flex", gap: 16, flexWrap: "wrap" }}>{investments.map((p) => { const d = PORTFOLIOS.find((x) => x.id === p.id); return <div key={p.id} style={{ display: "flex", alignItems: "center", gap: 5 }}><div style={{ width: 8, height: 8, borderRadius: 4, background: d?.color }} /><span style={{ fontSize: 11, color: C.text2 }}>{d?.name}</span></div>; })}</div></Card></div>
    <div style={{ padding: "0 20px 20px", display: "flex", flexDirection: "column", gap: 10 }}>{investments.map((p) => { const d = PORTFOLIOS.find((x) => x.id === p.id); const g = p.currentValue - p.invested; const pct = p.invested > 0 ? ((p.currentValue - p.invested) / p.invested) * 100 : 0; const isO = selId === p.id;
      return (<div key={p.id}><Card><div onClick={() => setSelId(isO ? null : p.id)} style={{ padding: "14px 16px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}><div style={{ width: 40, height: 40, borderRadius: 12, background: d.color + "18", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22 }}>{d.icon}</div><div style={{ flex: 1 }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><span style={{ fontSize: 16, fontWeight: 600 }}>{d.name}</span><span style={{ fontSize: 11, color: C.text3, background: C.bg, padding: "2px 8px", borderRadius: 6 }}>{d.type}</span></div><div style={{ fontSize: 12, color: C.text3, marginTop: 3 }}>{p.monthlyDCA > 0 ? "DCA " + fmt(p.monthlyDCA) + "/mois \u00b7 " : ""}Investi {fmt(p.invested)}</div></div><div style={{ textAlign: "right" }}><div style={{ fontSize: 16, fontWeight: 700 }}>{fmt(p.currentValue)}</div><div style={{ fontSize: 13, fontWeight: 600, color: g >= 0 ? C.green : C.red }}>{fmtPct(pct)}</div></div><Sparkline data={(p.history || []).map((h) => ({ value: h.value }))} color={d.color} /></div>
        {isO && <div style={{ borderTop: ".5px solid " + C.separator, padding: "12px 16px 16px" }}><div style={{ display: "flex", gap: 10, marginBottom: 14 }}><MiniStat label="Investi" value={fmt(p.invested)} /><MiniStat label="Valeur" value={fmt(p.currentValue)} /><MiniStat label="Gain" value={(g >= 0 ? "+" : "") + fmt(g)} color={g >= 0 ? C.green : C.red} /></div><div style={{ fontSize: 12, fontWeight: 600, color: C.text2, textTransform: "uppercase", letterSpacing: .5, marginBottom: 8 }}>Composition</div>{p.holdings.length === 0 ? <Empty text="Vide" /> : p.holdings.map((h, i) => (<div key={i} style={{ display: "flex", alignItems: "center", gap: 10, padding: "6px 0" }}><div style={{ flex: 1 }}><div style={{ fontSize: 14, fontWeight: 500 }}>{h.name}</div>{h.ticker && <div style={{ fontSize: 11, color: C.text3 }}>{h.ticker}</div>}</div><div style={{ width: 60, height: 3, background: C.separator, borderRadius: 2, overflow: "hidden" }}><div style={{ width: h.allocation + "%", height: "100%", background: d.color, borderRadius: 2 }} /></div><div style={{ fontSize: 13, fontWeight: 600, color: C.text2, minWidth: 36, textAlign: "right" }}>{h.allocation}%</div></div>))}<div style={{ fontSize: 12, fontWeight: 600, color: C.text2, textTransform: "uppercase", letterSpacing: .5, marginTop: 14, marginBottom: 8 }}>Historique</div><div style={{ maxHeight: 160, overflowY: "auto" }}>{(p.history || []).length === 0 ? <Empty text="Vide" /> : [...p.history].reverse().map((h, i) => { const hp = h.invested > 0 ? ((h.value - h.invested) / h.invested) * 100 : 0; return <div key={i} style={{ display: "flex", alignItems: "center", padding: "6px 0", borderTop: i > 0 ? ".5px solid " + C.separator : "none" }}><div style={{ fontSize: 13, color: C.text2, flex: 1 }}>{new Date(h.date).toLocaleDateString("fr-BE", { month: "short", year: "numeric" })}</div><div style={{ fontSize: 13, fontWeight: 500, marginRight: 12 }}>{fmt(h.value)}</div><div style={{ fontSize: 12, fontWeight: 600, color: hp >= 0 ? C.green : C.red, minWidth: 50, textAlign: "right" }}>{fmtPct(hp)}</div></div>; })}</div><button onClick={() => setShowUp(true)} style={{ marginTop: 12, width: "100%", padding: 10, borderRadius: 10, border: "none", background: d.color + "15", color: d.color, fontSize: 14, fontWeight: 600, cursor: "pointer" }}>MAJ valeur</button></div>}
      </Card></div>); })}</div>
    {showUp && <UpModal inv={investments} onUp={hUp} onClose={() => setShowUp(false)} />}
  </div>);
}
function UpModal({ inv, onUp, onClose }) {
  const [sel, setSel] = useState(inv[0]?.id || ""); const [val, setVal] = useState(""); const cur = inv.find((p) => p.id === sel);
  return (<><Backdrop onClick={onClose} /><ModalSheet><h3 style={{ margin: "0 0 16px", fontSize: 18, fontWeight: 600 }}>Mettre &agrave; jour</h3><div style={{ display: "flex", gap: 8, marginBottom: 14 }}>{inv.map((p) => { const d = PORTFOLIOS.find((x) => x.id === p.id); return <button key={p.id} onClick={() => { setSel(p.id); setVal(""); }} style={{ flex: 1, padding: "10px 8px", borderRadius: 10, border: "none", background: sel === p.id ? d.color : C.bg, color: sel === p.id ? "white" : C.text2, fontSize: 12, fontWeight: 600, cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}><span style={{ fontSize: 20 }}>{d.icon}</span>{d.name}</button>; })}</div>{cur && <div style={{ fontSize: 13, color: C.text2, marginBottom: 10, padding: "8px 12px", background: C.bg, borderRadius: 8 }}>Actuelle : <strong>{fmt(cur.currentValue)}</strong></div>}<div style={{ position: "relative" }}><input type="number" placeholder="Nouvelle valeur" value={val} onChange={(e) => setVal(e.target.value)} style={{ ...inputStyle, fontSize: 20, fontWeight: 700, paddingRight: 32 }} onFocus={focusBorder} onBlur={blurBorder} /><span style={{ position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", color: C.text3, fontSize: 16 }}>&euro;</span></div><SubmitBtn disabled={!Number(val)} onClick={() => Number(val) && onUp(sel, Number(val))} text="Enregistrer" /></ModalSheet></>);
}
function AddTxModal({ onAdd, onClose }) {
  const [type, setType] = useState("expense"); const [label, setLabel] = useState(""); const [amount, setAmount] = useState(""); const [cat, setCat] = useState("courses_b"); const [date, setDate] = useState(toKey(new Date())); const ref = useRef(null);
  useEffect(() => { setTimeout(() => ref.current?.focus(), 100); }, []);
  const cats = type === "income" ? BUDGET_CATS.income : BUDGET_CATS.expense;
  useEffect(() => { setCat(cats[0].id); }, [type]);
  const v = label.trim() && Number(amount) > 0;
  return (<><Backdrop onClick={onClose} /><ModalSheet><h3 style={{ margin: "0 0 16px", fontSize: 18, fontWeight: 600 }}>Nouvelle transaction</h3><div style={{ display: "flex", gap: 8, marginBottom: 14 }}>{[{ id: "expense", label: "D\u00e9pense", c: C.red }, { id: "income", label: "Revenu", c: C.green }].map((t) => (<button key={t.id} onClick={() => setType(t.id)} style={{ flex: 1, padding: 10, borderRadius: 10, border: "none", fontSize: 14, fontWeight: 600, background: type === t.id ? t.c : C.bg, color: type === t.id ? "white" : C.text2, cursor: "pointer" }}>{t.label}</button>))}</div><input ref={ref} type="text" placeholder="Libell\u00e9" value={label} onChange={(e) => setLabel(e.target.value)} style={inputStyle} onFocus={focusBorder} onBlur={blurBorder} /><div style={{ display: "flex", gap: 10, marginTop: 10, marginBottom: 14 }}><div style={{ flex: 1, position: "relative" }}><input type="number" placeholder="Montant" value={amount} onChange={(e) => setAmount(e.target.value)} style={{ ...inputStyle, paddingRight: 32 }} onFocus={focusBorder} onBlur={blurBorder} /><span style={{ position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", color: C.text3, fontSize: 16 }}>&euro;</span></div><input type="date" value={date} onChange={(e) => setDate(e.target.value)} style={{ ...inputStyle, padding: "14px 12px", fontSize: 14 }} /></div><div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 18 }}>{cats.map((c) => (<button key={c.id} onClick={() => setCat(c.id)} style={{ padding: "8px 12px", borderRadius: 10, border: cat === c.id ? "2px solid " + c.color : "1.5px solid " + C.separator, background: cat === c.id ? c.color + "15" : "transparent", color: cat === c.id ? c.color : C.text2, fontSize: 13, fontWeight: 500, cursor: "pointer", display: "flex", alignItems: "center", gap: 5 }}>{c.icon} {c.label}</button>))}</div><SubmitBtn disabled={!v} onClick={() => v && onAdd({ label: label.trim(), amount: Number(amount), type, category: cat, date })} text="Ajouter" /></ModalSheet></>);
}
